### ISSUE TITLE
Update latest_reconstructions script to write files named with cell specimen id

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#169]
As a software engineer, I want to make it easy to generate files ready for release, so that I can quickly deliver them without spending a lot of hands-on time.

Solution may be to modify this script so that it outputs three files for each cell, named with the LIMS id of the cell specimen.
https://github.com/AllenInstitute/neuron_morphology/blob/dev/pipeline/user_scripts/latest_reconstructions.py

An optional input should be a list of neuron reconstruction ids, in order to download just the files for that input set.

Example
758312441.marker
758312441_raw.swc
758312441_transformed.swc

Acceptance criteria:
- [x] Team member can easily generate the three files, named correctly, for each cell that has been processed.
- [x] Team member can generate the three files with an input list of neuron reconstruction ids to get just the files for that set.

**Comment by sgratiy** [comment]
@wbwakeman do you need files named based on the specimen_id or reconstruction_id?

**Comment by wbwakeman** [comment]
specimen id

**Comment by wbwakeman** [comment]
Example command:

```
python ./pipeline/user_scripts/latest_reconstructions.py nm-stage-deployment-out-runs ~/allen_dev/sandbox/neuron_morphology/test_latest_reconstructions/ --reconstruction_ids 1018012596 1015971405
```

Replace the output folder (2nd argument) with your own, and make sure your aws credentials are up to date

You can remove the ids to get all, and you can add random numbers to see the warning message you get when the id isn't found

Note that the script is not downloaded with the python module.  Need to get it separately and install any dependencies (i.e. 'boto3')
