### ISSUE TITLE
Add Hausdorff dimension to morphological features

### ISSUE THREAD

**Issue by MKRangers** [AllenInstitute/neuron_morphology#177]
**Describe the use case that is addressed by this feature.**
Morphological features used for cell type analysis on fMOST have been including Hausdorff dimension. We would like to see this feature to be included in your morph-feature computation pipeline.

**Describe the solution you'd like**
Just add Hausdorff dimension as part of feature dictionary output.

**Describe alternatives you've considered**
No alternatives needed.

**Additional context**
As described in the use case.

**Do you want to work on this issue?**
No. It's the best for you to keep your code style consistent.

**Comment by wbwakeman** [comment]
@MKRangers Can you point towards an implementation of Hausdorff dimension?

**Comment by wbwakeman** [comment]
This feature was deemed not important enough for the team to implement to support the next release.
