### ISSUE TITLE
Generate transformed SWC files for Q2 2021 release

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#195]
LIMS query to identify the neuron reconstruction records for Lein U01 grant Q2 data push to BICCN archives.  80 reconstructions expected

```
SELECT nr.id AS neuron_reconstruction_id
FROM specimens sp JOIN ephys_roi_results er On er.id=sp.ephys_roi_result_id AND er.workflow_state = 'manual_passed' 
JOIN neuron_reconstructions nr ON nr.specimen_id=sp.id AND nr.superseded = 'f' AND nr.manual = 't'
JOIN well_known_files wkf ON wkf.attachable_id=nr.id AND wkf.well_known_file_type_id = (SELECT id FROM well_known_file_types WHERE name = '3DNeuronReconstruction') 
JOIN donors d ON d.id=sp.donor_id 
WHERE 
er.published_at = '3021-06-30' AND wkf.published_at = '3021-06-30'
--er.published_at IS NOT NULL AND wkf.published_at IS NOT NULL --uncomment to get all published reconstructions ever
ORDER BY 1;
```
related to #127

Tasks:
- [x] Use Neuron morphology pipeline to create transformed versions of the reconstruction files
- [ ] Run [migrate_outputs ](https://github.com/AllenInstitute/neuron_morphology/blob/dev/pipeline/commands/lambdas/migrate_outputs.py)lambda
- [ ] Run latest_reconstructions.py script
- [x] Make the files available to Wayne

**Comment by wbwakeman** [comment]
All 80 reconstructions were enqueued in the LIMS MORPHOLOGY_DATA_MOVE_QUEUE so that they transferred to AWS and started the neuron_morphology pipeline.  All step functions succeeded.  Just need someone to run the script to download the files now.

**Comment by wbwakeman** [comment]
```
python latest_reconstructions.py nm-stage-deployment-out-runs /allen/aibs/technology/waynew/morph/20210630_swc/download/ --reconstruction_ids 1018012596 703291074 706963251 706967287
```
This command seems to work but there are not entries for the new reconstructions in the list above.  Maybe an action needs to be taken to populate them in the table??

**Comment by gnayuy** [comment]
The all runs results are available at nm-prod-deployment-working-bucket, so I download all runs results including 80 neurons from there to /allen/programs/celltypes/workgroups/mouse_full_morphology/yangy/swc_q2_2021. 

The nm-prod might be a little bit behind the dev branch for release, I'll look into it.
