### ISSUE TITLE
morphology pipeline design goals

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#45]
Define each of these items in more detail:
Performance requirements
reporting requirements
storage
exception handling
versioning of modules, and data
data releases
deployment
security
cost
lifecycle plan

For each, write down specifically what it means for that entry.  i.e. what are the items that need to be considered to address it.
Are there performance objectives?

**Comment by NileGraddis** [comment]
We've gathered some requirements from stakeholders here:
http://confluence.corp.alleninstitute.org/display/~matthew.aitken/Morphology+API+Requirements

An important piece of work is to synthesize these.
