### ISSUE TITLE
Design morphology pipeline

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#47]
Write clear goals and approach document
Get feedback
Turn into a structured and clear design document
Define steps needed to implement i.e. create issues

**Comment by wbwakeman** [comment]
FYI: http://confluence.corp.alleninstitute.org/display/IT/AWS+Account+Onboarding+Process

**Comment by NileGraddis** [comment]
nb: draw.io is a handy tool for architecture diagrams

**Comment by NileGraddis** [comment]
also, here is the document: http://confluence.corp.alleninstitute.org/display/~matthew.aitken/Morphology+Pipeline+Design+Document
