### ISSUE TITLE
Neuron Morphology Feature Extractor Hackathon

### ISSUE THREAD

**Issue by MatthewAitken** [AllenInstitute/neuron_morphology#84]
Hold Hackathon with IVSCC, FMOST, and EM scientists

- [ ] test on windows [in progress]
- [ ] test on mac
- [x] pypi deployment
- [x] remove old, terrible code
- [ ] Work with PM to schedule

**Comment by wbwakeman** [comment]
Tracking CircleCI credits issue for Windows builds

**Comment by wbwakeman** [comment]
Windows and Mac builds tracked in new issue
