### ISSUE TITLE
Create component to move data from LIMS to neuron_morphology pipeline

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/neuron_morphology#98]
consists of a LIMS strategy and executable, and job_queue
Gather data from LIMS
  SWC files
  images and dimensions
  layer drawings (?)
  pia drawings
  white matter drawings
  numbers, such as scale transform
  upright transform, including pin location
zips data into an archive
uses boto3 to post to known S3 bucket

**Comment by gnayuy** [comment]
Sergey add a LIMS strategy and job_queue. I developed python executable to post data to s3 landing bucket. The integration test works as expected.
